version: '3.8'

services:
  # Serviço PHP-FPM
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: php-fpm
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    networks:
      - app-network
    extra_hosts:
      - host.docker.internal:host-gateway

  # Serviço MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_telegram_bot_test_bd
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # Servidor NGINX (opcional)
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
